"""Empirical-Bayes Gaussian hierarchical partial pooling.

The boundary is explicit: the layer consumes subject-level approximately
Gaussian parameter likelihoods (theta_hat_s, V_s) generated by the
subject-level inference engine. Hyperparameters are estimated from cohort and
population moments; conditional posteriors are then available in closed form.
This is a stable population layer, not a claim of a raw-observation joint
posterior.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class SubjectEstimate:
    subject_id: str
    cohort: str
    mean: np.ndarray
    covariance: np.ndarray

    def __post_init__(self) -> None:
        m = np.asarray(self.mean, dtype=float)
        V = np.asarray(self.covariance, dtype=float)
        if m.ndim != 1 or V.shape != (m.size, m.size):
            raise ValueError("invalid subject estimate dimensions")
        if not np.all(np.isfinite(m)) or not np.all(np.isfinite(V)):
            raise ValueError("subject estimates must be finite")
        V = 0.5 * (V + V.T)
        eig = np.linalg.eigvalsh(V)
        if eig.min() <= 0:
            raise ValueError("subject covariance must be positive definite")
        object.__setattr__(self, "mean", m)
        object.__setattr__(self, "covariance", V)


@dataclass(frozen=True)
class HierarchicalFit:
    global_mean: np.ndarray
    cohort_means: dict[str, np.ndarray]
    subject_posterior_means: dict[str, np.ndarray]
    subject_posterior_covariances: dict[str, np.ndarray]
    within_cohort_covariance: np.ndarray
    cohort_covariance: np.ndarray
    n_iter: int
    converged: bool
    log_evidence_proxy: float


def _regularized_spd(A: np.ndarray, floor: float = 1e-8) -> np.ndarray:
    A = 0.5 * (A + A.T)
    vals, vecs = np.linalg.eigh(A)
    vals = np.maximum(vals, floor)
    return vecs @ np.diag(vals) @ vecs.T


def _sample_cov(X: np.ndarray, p: int) -> np.ndarray:
    if len(X) <= 1:
        return np.eye(p)
    return np.atleast_2d(np.cov(X.T, bias=True))


def fit_partial_pooling(
    estimates: list[SubjectEstimate],
    *,
    max_iter: int = 1,
    tol: float = 1e-7,
    covariance_floor: float = 1e-8,
    damping: float = 1.0,
) -> HierarchicalFit:
    """Fit a stable empirical-Bayes Gaussian hierarchy by moment estimation.

    Model:
        theta_s | mu_g, Sigma ~ N(mu_g, Sigma)
        mu_g | mu0, Tau       ~ N(mu0, Tau)
        theta_hat_s | theta_s  ~ N(theta_s, V_s)

    The moment hyperparameters are estimated once from the observed
    subject-level summaries, then the conditional Gaussian posteriors are
    computed exactly. ``max_iter``, ``tol`` and ``damping`` are retained for
    API stability; this implementation is intentionally non-iterative because
    the closed-form boundary is more robust than an unguarded EM loop for
    small cohort counts.
    """
    if not estimates:
        raise ValueError("at least one subject estimate is required")
    if not (0.0 < damping <= 1.0):
        raise ValueError("damping must be in (0, 1]")
    p = estimates[0].mean.size
    if any(e.mean.size != p for e in estimates):
        raise ValueError("all subject estimates must share parameter dimension")

    cohorts = sorted({e.cohort for e in estimates})
    grouped = {g: [e for e in estimates if e.cohort == g] for g in cohorts}
    raw = np.vstack([e.mean for e in estimates])
    global_mean = raw.mean(axis=0)

    # Conservative moment estimate of within-cohort biological heterogeneity.
    # We intentionally do not subtract measurement covariance here: with small
    # cohorts that correction can make Sigma nearly singular and destabilize
    # the hierarchical precision algebra. Measurement uncertainty remains in
    # the exact subject-level posterior below.
    raw_cohort_means: dict[str, np.ndarray] = {}
    within_terms: list[np.ndarray] = []
    for g, es in grouped.items():
        X = np.vstack([e.mean for e in es])
        raw_cohort_means[g] = X.mean(axis=0)
        within_terms.append(_sample_cov(X, p) if len(es) > 1 else np.eye(p))
    Sigma = _regularized_spd(np.mean(within_terms, axis=0), covariance_floor)

    # Cohort covariance is the dispersion of cohort means around the global
    # mean. A regularized moment estimate is deliberately preferred to a noisy
    # deconvolution of cohort-mean measurement error.
    cohort_matrix = np.vstack(list(raw_cohort_means.values()))
    Tau_raw = _sample_cov(cohort_matrix, p) if len(cohorts) > 1 else np.eye(p)
    Tau = _regularized_spd(Tau_raw, covariance_floor)

    Sigma_inv = np.linalg.inv(Sigma)
    Tau_inv = np.linalg.inv(Tau)
    cohort_means: dict[str, np.ndarray] = {}
    cohort_post_covariances: dict[str, np.ndarray] = {}
    for g, es in grouped.items():
        Cg = _regularized_spd(np.linalg.inv(Tau_inv + len(es) * Sigma_inv), covariance_floor)
        rhs = Tau_inv @ global_mean + Sigma_inv @ sum((e.mean for e in es), np.zeros(p))
        candidate = Cg @ rhs
        # damping is only a deterministic shrinkage knob relative to the raw
        # cohort estimate; it never enters the subject-level likelihood.
        cohort_means[g] = (1.0 - damping) * raw_cohort_means[g] + damping * candidate
        cohort_post_covariances[g] = Cg

    subject_post_m: dict[str, np.ndarray] = {}
    subject_post_C: dict[str, np.ndarray] = {}
    for e in estimates:
        Vi = np.linalg.inv(e.covariance)
        C = _regularized_spd(np.linalg.inv(Sigma_inv + Vi), covariance_floor)
        m = C @ (Sigma_inv @ cohort_means[e.cohort] + Vi @ e.mean)
        subject_post_m[e.subject_id] = m
        subject_post_C[e.subject_id] = C

    proxy = 0.0
    for e in estimates:
        C = Sigma + e.covariance
        diff = e.mean - cohort_means[e.cohort]
        sign, logdet = np.linalg.slogdet(C)
        if sign > 0:
            proxy += -0.5 * (p * np.log(2*np.pi) + logdet + diff @ np.linalg.solve(C, diff))

    return HierarchicalFit(
        global_mean=global_mean,
        cohort_means=cohort_means,
        subject_posterior_means=subject_post_m,
        subject_posterior_covariances=subject_post_C,
        within_cohort_covariance=Sigma,
        cohort_covariance=Tau,
        n_iter=1,
        converged=True,
        log_evidence_proxy=float(proxy),
    )
