"""Runtime contracts for publishing real scientific pipeline results to the UI.

The contract deliberately separates source observations, posterior state,
PET kinetic uncertainty, provenance, point-in-time availability and OOS status.
No synthetic/reference result is permitted through the production runtime path.
"""
from __future__ import annotations

from datetime import datetime, timezone
from enum import StrEnum
from typing import Any

import numpy as np
from pydantic import BaseModel, ConfigDict, Field, field_validator

from neuro_twin.data.schema import Observation


class RuntimeClass(StrEnum):
    RESEARCH_OBSERVATIONAL = "research_observational"
    CONTROLLED_RESEARCH = "controlled_research"
    SYNTHETIC_REFERENCE = "synthetic_reference"


class RuntimeStatus(StrEnum):
    PUBLISHED = "PUBLISHED"
    REJECTED = "REJECTED"
    WAITING = "WAITING"


class PosteriorState(BaseModel):
    model_config = ConfigDict(extra="forbid")

    names: tuple[str, ...] = ("P", "I", "N", "Q")
    mean: list[float] = Field(min_length=4, max_length=4)
    covariance: list[list[float]]
    time_months: float

    @field_validator("mean")
    @classmethod
    def finite_mean(cls, value: list[float]) -> list[float]:
        if not np.all(np.isfinite(np.asarray(value, dtype=float))):
            raise ValueError("posterior mean must be finite")
        return value

    @field_validator("covariance")
    @classmethod
    def valid_covariance(cls, value: list[list[float]]) -> list[list[float]]:
        cov = np.asarray(value, dtype=float)
        if cov.shape != (4, 4) or not np.all(np.isfinite(cov)):
            raise ValueError("state covariance must be a finite 4x4 matrix")
        if not np.allclose(cov, cov.T, atol=1e-10):
            raise ValueError("state covariance must be symmetric")
        eig = np.linalg.eigvalsh(cov)
        if eig.min() < -1e-10:
            raise ValueError("state covariance must be positive semidefinite")
        return value

    def ci95(self) -> dict[str, float]:
        sd = np.sqrt(np.maximum(np.diag(np.asarray(self.covariance, dtype=float)), 0.0))
        return {name: float(1.96 * s) for name, s in zip(self.names, sd)}


class PETKineticPosterior(BaseModel):
    """Posterior of PET kinetic observables after AIF/frame uncertainty propagation."""

    model_config = ConfigDict(extra="forbid")

    names: tuple[str, ...]
    mean: list[float]
    covariance: list[list[float]]
    uncertainty_sources: tuple[str, ...] = ()
    kinetic_model: str
    inference_version: str

    @field_validator("mean")
    @classmethod
    def finite_values(cls, value: list[float]) -> list[float]:
        if not np.all(np.isfinite(np.asarray(value, dtype=float))):
            raise ValueError("PET posterior mean must be finite")
        return value

    @field_validator("covariance")
    @classmethod
    def validate_covariance(cls, value: list[list[float]], info):
        mean = info.data.get("mean")
        cov = np.asarray(value, dtype=float)
        if mean is None or cov.shape != (len(mean), len(mean)):
            raise ValueError("PET kinetic covariance shape mismatch")
        if not np.all(np.isfinite(cov)) or not np.allclose(cov, cov.T, atol=1e-10):
            raise ValueError("PET kinetic covariance must be finite and symmetric")
        if np.linalg.eigvalsh(cov).min() < -1e-10:
            raise ValueError("PET kinetic covariance must be positive semidefinite")
        return value


class PETNeuroBinding(BaseModel):
    """Linearization of the registered PET→Neuro-Twin observation operator.

    h_pet(x, theta) ≈ h0 + Hx (x-x0) + Htheta (theta-theta0)

    The adapter does not invent Hx/Htheta. They must be generated by the
    scientific model registry and carry their own version identifier.
    """

    model_config = ConfigDict(extra="forbid")

    model_name: str = Field(min_length=1)
    model_version: str = Field(min_length=1)
    observable_names: tuple[str, ...]
    reference_state: list[float] = Field(min_length=4, max_length=4)
    predicted_at_reference: list[float]
    jacobian_state: list[list[float]]
    jacobian_parameters: list[list[float]] | None = None
    parameter_mean: list[float] | None = None
    parameter_covariance: list[list[float]] | None = None
    parameter_names: tuple[str, ...] | None = None
    assumptions: tuple[str, ...] = ()


class PITEnvelope(BaseModel):
    model_config = ConfigDict(extra="forbid")

    as_of: datetime
    acquisition_max: datetime
    result_max: datetime
    ingest_time: datetime

    @field_validator("as_of", "acquisition_max", "result_max", "ingest_time")
    @classmethod
    def aware(cls, value: datetime) -> datetime:
        if value.tzinfo is None:
            raise ValueError("PIT timestamps must be timezone-aware")
        return value.astimezone(timezone.utc)


class OOSResult(BaseModel):
    model_config = ConfigDict(extra="forbid")

    status: str
    temporal_leakage: bool
    metrics: dict[str, float] = {}


class RuntimeProvenance(BaseModel):
    model_config = ConfigDict(extra="forbid")

    source_name: str = Field(min_length=1)
    dataset_id: str = Field(min_length=1)
    dataset_version: str = Field(min_length=1)
    model_version: str = Field(min_length=1)
    processing_pipeline: str = Field(min_length=1)
    processing_version: str = Field(min_length=1)
    raw_hashes: tuple[str, ...] = ()
    feature_hashes: tuple[str, ...] = ()
    observation_hash: str = Field(min_length=1)
    result_hash: str | None = None
    retrieval_uri: str | None = None
    access_tier: str = Field(min_length=1)


class RuntimeResult(BaseModel):
    model_config = ConfigDict(extra="forbid")

    runtime_id: str = Field(min_length=1)
    runtime_class: RuntimeClass
    subject_id: str = Field(min_length=1)
    event_id: str = Field(min_length=1)
    produced_at: datetime
    pit: PITEnvelope
    provenance: RuntimeProvenance
    observations: list[Observation] = Field(min_length=1)
    state_prior: PosteriorState
    state_posterior: PosteriorState
    pet_kinetic_posterior: PETKineticPosterior | None = None
    pet_neuro_binding: PETNeuroBinding | None = None
    oos: OOSResult | None = None
    trajectory: dict[str, Any] | None = None
    prediction: dict[str, Any] | None = None
    evidence: dict[str, Any] = {}

    @field_validator("produced_at")
    @classmethod
    def produced_at_aware(cls, value: datetime) -> datetime:
        if value.tzinfo is None:
            raise ValueError("produced_at must be timezone-aware")
        return value.astimezone(timezone.utc)

    @field_validator("observations")
    @classmethod
    def observations_have_provenance(cls, value: list[Observation]) -> list[Observation]:
        for obs in value:
            if not obs.quality.provenance_complete:
                raise ValueError(f"observation {obs.event_id}/{obs.feature} lacks complete provenance")
            if not obs.provenance.source_version:
                raise ValueError(f"observation {obs.event_id}/{obs.feature} lacks source_version")
            if obs.result_time is not None and obs.ingest_time < obs.result_time:
                raise ValueError("ingest_time cannot precede result_time")
        return value
